#Input Data from Nanopore Sequencer: pod5 format
#specify the path to a directory (in "") in which your .pod5 files are stored
pod5_input: "/data/home/the/experiments/EX_THE000016/pod5_Gutachten2"

#basecalling configurations
#choose a model which is used for basecalling.
#in general there are three types of model supplied by epi2me
#fast, high accuracy (hac), super accurate (sup)
#as the names suggest the models are increassingly more accurate, but become slower from left to right. Choose one listed here https://github.com/nanoporetech/dorado#available-basecalling-models
basecaller_model: "dna_r10.4.1_e8.2_400bps_fast@v5.0.0"
#reads with average qualtiy scores of >= qscore_filter are kept. Otherwise they are discarded
qscore_filter: 10 
